services:
  - type: web
    name: murgo-api
    runtime: node
    rootDir: backend
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: "20.14.0"
